export const LOAD_PLAYBACK_SUCCESS = 'LOAD_PLAYBACK_SUCCESS';
export const LOAD_CREDITS_SUCCESS = 'LOAD_CREDITS_SUCCESS';
export const LOAD_ARTIST_SUCCESS = 'LOAD_ARTIST_SUCCESS';
export const LOAD_ALBUM_SUCCESS = 'LOAD_ALBUM_SUCCESS';
export const SET_PROGRESS = 'SET_PROGRESS';
