export const SPOTIFY_LOAD_CONFIG = 'SPOTIFY_LOAD_CONFIG';
export const SPOTIFY_AUTHENTICATION_SUCCESS = 'SPOTIFY_AUTHENTICATION_SUCCESS';

export const LOAD_SAVED_TRACKS_PAGE_SUCCESS = 'LOAD_SAVED_TRACKS_PAGE_SUCCESS';
export const LOAD_SAVED_ALBUMS_PAGE_SUCCESS = 'LOAD_SAVED_ALBUMS_PAGE_SUCCESS';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
